# Generated by Django 6.0.2 on 2026-02-09 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Конкретное действие, которое нужно выполнить",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли привычка приятной (вознаграждением)",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки для напоминания в днях (от 1 до 7)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Привычки можно публиковать в общий доступ",
                        verbose_name="Публичная привычка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой (только для полезных привычек)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_date", models.DateField(verbose_name="Дата выполнения")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время выполнения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-completion_date"],
                "unique_together": {("habit", "completion_date")},
            },
        ),
    ]
